notifications:
  email: false

language: python

sudo: false

addons:
  postgresql: "9.6"
  apt:
    packages:
      - postgresql-9.6-postgis-2.3

matrix:
  include:
    - python: 3.5
      env: TOXENV=py35-1.8
    - python: 3.5
      env: TOXENV=py35-1.11

env:
  global:
    - CFLAGS="-O0"
  matrix:
    - TOXENV=flake8
    - TOXENV=py27-1.8
    - TOXENV=py27-1.11

install:
  - pip install tox codecov
before_script:
  - 'if [ $TOXENV != "flake8" ]; then .travis/before_script; fi'
script:
  - tox
after_success:
  - codecov
