version: '3.3'

services:
  db:
    image: mdillon/postgis:9.5
    ports:
      - "54321:5432"
    environment:
      - POSTGRES_USER=mapit
      - POSTGRES_PASSWORD=mapit
      - POSTGRES_DB=mapit
      - PGUSER=mapit
      - PGPASSWORD=mapit

  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./:/src/mapit_africa
    environment:
      - DJANGO_SETTINGS_MODULE=project.settings
      - DATABASE_URL=postgresql://mapit:mapit@db:5432/mapit
      - DJANGO_SECRET_KEY=somethingsecret
      - PGHOST=db
      - PGDATABASE=mapit
      - PGUSER=mapit
      - PGPASSWORD=mapit
      - PYTHONDONTWRITEBYTECODE="True"
      # - DJANGO_DEBUG=False  # For testing deploys
